---
batnet_role: server

server_packages:
  - cockpit
  - podman
  - 389-ds-base

server_image_name: localhost/server
server_tag: latest
server_containerfile: ansible/roles/batnet/files/endpoint.Containerfile

client_packages:
  - steam
  - bottles
  - sunshine
  - mangohud

client_image_name: localhost/client
client_tag: latest
client_containerfile: ansible/roles/batnet/files/endpoint.Containerfile

batnet_image_signing_enabled: false
batnet_image_signing_key: ""

cloud_packages:
  - caddy
  - wireguard-tools
  - openssh-server

cloud_image_name: localhost/cloud
cloud_tag: latest
cloud_containerfile: ansible/roles/batnet/files/cloud.Containerfile

batnet_host_configs:
  server:
    packages: "{{ server_packages }}"
    services:
      - cockpit.socket
  client:
    packages: "{{ client_packages }}"
    services: []
  cloud:
    packages: "{{ cloud_packages }}"
    services:
      - caddy
      - sshd

batnet_container_configs:
  server:
    image_name: "{{ server_image_name }}"
    default_tag: "{{ server_tag }}"
    nvidia_tag: nvidia
    containerfile: "{{ server_containerfile }}"
    use_base_arg: false
    supports_build_target: false
    build_actions:
      - build
      - build-no-cache
      - deploy
    deploy_action: deploy
    deploy_strategy: bootc
    supports_clean: true
    clean_target: "{{ server_image_name }}:{{ server_tag }}"
    supports_signing: true
  client:
    image_name: "{{ client_image_name }}"
    default_tag: "{{ client_tag }}"
    nvidia_tag: nvidia
    containerfile: "{{ client_containerfile }}"
    use_base_arg: false
    supports_build_target: false
    build_actions:
      - build
      - build-no-cache
      - deploy
    deploy_action: deploy
    deploy_strategy: bootc
    supports_clean: false
    supports_signing: true
  cloud:
    image_name: "{{ cloud_image_name }}"
    default_tag: "{{ cloud_tag }}"
    containerfile: "{{ cloud_containerfile }}"
    use_base_arg: false
    supports_build_target: false
    build_actions:
      - build
      - build-no-cache
    supports_clean: false
