---
- name: Build container image
  ansible.builtin.shell: >-
    podman build --pull=newer
    {% if batnet_no_cache %} --no-cache {% endif %}
    -f {{ batnet_cfg.containerfile }}
    {% if batnet_cfg.use_base_arg | default(false) %} --build-arg BASE_IMAGE={{ batnet_target_base_image }}{% endif %}
    -t {{ batnet_target_image }}
    "{{ batnet_cfg.containerfile | dirname }}"
  args:
    chdir: "{{ playbook_dir }}/.."
